### ISSUE TITLE
Uncaught Error: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by jabba-jedi** [TimKam/atomic-vale#20]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.0-beta3 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atomic-vale](https://github.com/TimKam/atomic-vale) package 1.9.0

### Stack Trace

Uncaught Error: spawn ENAMETOOLONG

```
At C:\Users\myermakovich\AppData\Local\atom\app-1.39.0-beta3\resources\app\static\<embedded>:14

Error: spawn ENAMETOOLONG
    at ChildProcess.spawn (internal/child_process.js:357:11)
    at Object.spawn (child_process.js:540:9)
    at BufferedProcess.spawn (~/AppData/Local/atom/app-1.39.0-beta3/resources/app/static/<embedded>:14:1127048)
    at BufferedProcess.spawnWithEscapedWindowsArgs (~/AppData/Local/atom/app-1.39.0-beta3/resources/app/static/<embedded>:14:1125601)
    at BufferedProcess.start (~/AppData/Local/atom/app-1.39.0-beta3/resources/app/static/<embedded>:14:1125153)
    at new BufferedProcess (~/AppData/Local/atom/app-1.39.0-beta3/resources/app/static/<embedded>:14:1125019)
    at runLinter (/packages/atomic-vale/lib/init.coffee:80:25)
    at /packages/atomic-vale/lib/init.coffee:121:11
    at new Promise (<anonymous>)
    at Object.lint (/packages/atomic-vale/lib/init.coffee:120:16)
    at /packages/linter/lib/linter-registry.js:113:26
    at new Promise (<anonymous>)
    at _loop (/packages/linter/lib/linter-registry.js:111:9)
    at /packages/linter/lib/linter-registry.js:98:40)
    at Generator.next (<anonymous>)
    at /packages/linter/lib/linter-registry.js:178:4)
    at Generator.next (<anonymous>)
    at step (/packages/linter/lib/linter-registry.js:9:273)
    at /packages/linter/lib/linter-registry.js:9:443
    at new Promise (<anonymous>)
    at /packages/linter/lib/linter-registry.js:9:99)
    at /packages/linter/lib/main.js:114:30
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.39.0-beta3/resources/app/static/<embedded>:11:1207528)
    at Emitter.emit (~/AppData/Local/atom/app-1.39.0-beta3/resources/app/static/<embedded>:11:1208969)
    at EditorLinter.lint (/packages/linter/lib/editor-linter.js:52:18)
    at EditorRegistry.createFromTextEditor (/packages/linter/lib/editor-registry.js:47:20)
    at /packages/linter/lib/editor-registry.js:28:14
    at onDidAddTextEditor (~/AppData/Local/atom/app-1.39.0-beta3/resources/app/static/<embedded>:11:427504)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.39.0-beta3/resources/app/static/<embedded>:11:1207528)
    at Emitter.emit (~/AppData/Local/atom/app-1.39.0-beta3/resources/app/static/<embedded>:11:1208969)
```

### Commands

```
     -7:59.1.0 intentions:highlight (input.hidden-input)
     -7:59 core:paste (input.hidden-input)
     -7:56.6.0 command-palette:toggle (input.hidden-input)
     -7:51.1.0 markdown-preview:toggle (input.hidden-input)
  4x -4:21.8.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-dracula-syntax.theme-dracula-ui)
     -3:51.8.0 editor:newline (input.hidden-input)
  2x -3:03.6.0 core:move-right (input.hidden-input)
     -2:45.8.0 core:backspace (input.hidden-input)
  5x -1:49.8.0 editor:newline (input.hidden-input)
     -0:37.9.0 application:add-project-folder (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
atomic-vale 1.9.0 
busy-signal 2.0.1 
dracula-syntax 2.0.7 
dracula-ui 0.6.0 
intentions 1.1.5 
linter 2.3.0 
linter-markdown 5.2.9 
linter-remark 6.0.0 
linter-ui-default 1.7.1 
markdown-preview-enhanced 0.16.1 
pigments 0.40.2 
svg-preview 0.14.0 
teletype 0.13.4 
```

**Comment by TimKam** [comment]
Seems to be an issue with Windows if too many files are included. Ideally, it would be fixed somewhere upstream. Correct me if I'm wrong.
